name: Check status of the device_farm_gateway server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "*/5 * * * *"
    
jobs:
  cron:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x]
        python-version: ["3.8"]
        
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Noti
        run: python actions/check_device_farm_gateway.py
        env:
          DEVICE_FARM_GATEWAY_URL: http://gateway.devicefarm.netspresso.ai
          GATEWAY_SLACK_WEBHOOK_URL: ${{ secrets.GATEWAY_SLACK_WEBHOOK_URL }}